sudo: required

services:
  - docker

before_install:
  - docker build -t neerajjainwalmart/fib-react-client -f ./client/Dockerfile.dev ./client

script:
  - docker container run neerajjainwalmart/fib-react-client npm run test -- --coverage

after_success:
  - docker build -t neerajjainwalmart/fib-client ./client
  - docker build -t neerajjainwalmart/fib-nginx ./nginx
  - docker build -t neerajjainwalmart/fib-server ./server
  - docker build -t neerajjainwalmart/fib-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take all those images and push them to docker hub
  - docker push neerajjainwalmart/fib-client
  - docker push neerajjainwalmart/fib-nginx
  - docker push neerajjainwalmart/fib-server
  - docker push neerajjainwalmart/fib-worker
  
deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-731080115171
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY